name: wazo-cel-plugin
namespace: official
version: 2.4.1
author: Wazo Communication inc.
display_name: CEL API
min_wazo_version: 20.13
tags:
  - api
  - call_logs
  - cel
  - http
homepage: http://wazo-platform.org
